### ISSUE TITLE
Cloud.html

### ISSUE THREAD

**Issue by YogiBabaji** [techterbium/MSWebsite#1]
Vikky, 

Renamed the DevOps page to cloud.html . Working well in my local but prod I m unable to see the page.

**Comment by techterbium** [comment]
I hope, this is working now. It takes few minutes at times to get the changes reflected in production.

**Comment by techterbium** [comment]
I am able to see 404 in mobile version.

**Comment by techterbium** [comment]
Possible issue could be - because of the filename is case sensitive and C in Cloud.html is capital.

**Comment by YogiBabaji** [comment]
the renaming was done. Working well.

Please validate and we can close the issue.

**Comment by YogiBabaji** [comment]
Working well. Closing the issue
